spring:
  datasource:
    # 로컬 DB 접속 정보
    url: jdbc:mysql://localhost:3306/pickban_dev_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: test
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

verify-url: "http://localhost:4200/auth/verify?email=%s&token=%s"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.transaction: TRACE
