name: Deploy to AWS

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write # OIDC 인증을 위해 필수
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 소스 코드 가져오기
        uses: actions/checkout@v4

      - name: JDK 17 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Gradle 빌드
        run: |
          chmod +x gradlew
          ./gradlew bootJar -x test

      - name: AWS 권한 가져오기 (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::902878533887:role/GitHubActions-Deploy-Role
          aws-region: ap-northeast-2

      - name: Amazon ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 빌드 및 ECR 푸시
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pickban-server
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Copy Docker Compose file to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yml"     # GitHub에 있는 파일
          target: "/home/ec2-user/pickban-server/" # EC2의 목적지 폴더
          overwrite: true

      - name: EC2 배포 수행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
            
            docker pull ${{ steps.login-ecr.outputs.registry }}/pickban-server:latest
            
            # 컨테이너 재시작 (docker-compose가 있는 경로로 이동 필수)
            cd /home/ec2-user/pickban-server
            
            # GitHub Secrets에 저장된 .env 내용을 파일로 생성
            echo "${{ secrets.ENV_FILE }}" > .env
            
            docker-compose down
            docker-compose up -d
            
            # 미사용 이미지 정리
            docker image prune -f
